"""empty message

Revision ID: db70c50b1ae7
Revises:
Create Date: 2025-10-01 20:21:14.190600

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "db70c50b1ae7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
